name: learn github ci


on: 
  push:
    branches: ['main']


jobs:

  build:
    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v4
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: true
    - run: npm ci
    - run: npm test

